<?php

/**
 * @file
 * Allows users to subscribe to Mailman mailing lists via a form in
 * their user profile.  List of mailing lists is defined by adminstrator.
 * Module maintains a list of user subscriptions and passwords.
 * Module sends requests for subscription changes to Mailman request address.
 */

/**
 * Implementation of hook_help().
 */
function mailman_manager_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('Utilities related to Mailman manager, subscription system and database for Mailman mailing lists.');
  }
}

/**
 * Implementation of hook_link().
 */
function mailman_manager_link($type, $node = NULL, $teaser = FALSE) {
  $links = array();

  if ($type == 'page' && user_access('access content')) {
//    $links[] = l(t('mailing %list', array('%list' => format_plural(_mailman_manager_get_count(), 'list', 'lists'))), 'mailman_manager', array('title' => t('Subscribe to mailing %list', array('%list' => format_plural(_mailman_manager_get_count(), 'list', 'lists')))));
    $links[] = l(t('mailing lists'), 'mailman_manager', array('title' => t('Subscribe to mailing lists')));
  }

  return $links;
}

/**
 * Implementation of hook_perm().
 */
function mailman_manager_perm() {
  return array('access mailman_manager', 'administer mailman_manager');
}

/**
 * Implementation of hook_menu().
 */
function mailman_manager_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array('path' => 'mailman_manager',
      'title' => ('mailing lists'),
      'callback' => 'mailman_manager_page',
      'access' => user_access('access mailman_manager'),
      'type' => MENU_NORMAL_ITEM);

    $items[] = array('path' => 'admin/mailman_manager',
      'title' => t('mailing lists'),
      'access' => user_access('administer mailman_manager'),
      'callback' => 'mailman_manager_admin',
      'type' => MENU_NORMAL_ITEM);
  }
  return $items;
}

/**
 * Menu callback; Forwards request to hook_user;
 */
function mailman_manager_page() {
  global $user;
  if (!user_access('access mailman_manager')) {
    print theme('page', 'You must be an authorized member to subscribe to mailing lists');
  }
  else {
    drupal_goto('user/'.$user->uid.'/edit/mailman_manager');
  }
}

/**
* Implementation of hook_user()
* Checks whether an email address is subscribed to the mailinglist
* when a new user signs up. If so, changes uid from 0 to the new uid
* in sn_subscriptions so that the user's subscription status is known
* when he logs in.
*/
function mailman_manager_user($op, &$edit, &$account, $category=NULL) {
  switch ($op) {
  //Create menu option on user tab;
    case 'categories':
      $output_user[] = array('name' => 'mailman_manager', 'title' => t('mailing lists'), 'weight' => 9);
    return $output_user;
    break;

  //List mailing lists with user subscriptions and options;
    case 'form':
    if ($category=='mailman_manager' && user_access('access mailman_manager')){
    $output = '<div class="mailman_manager">';
    $output .='<p>'.t('The following email address will be subscribed to the email lists:');
    $output .='<br><strong>'.$account->mail.'</strong>';
    $output .=t('<p>If you would like to have a different email address subscribed, change your email address in the account settings tab.');
    $lists = _mailman_manager_get_lists();
	$fields['lists'] = array(
		'#type' => 'fieldset',
		'#prefix' => $output
	);
    if (count($lists) == 0) {
      $output = t('There are no lists available for subscription.');
    } else {
		$status = 0;
		foreach ($lists as $list){
	        $subscrip=_mailman_manager_get_subscriptions($account->uid,$list[lid]);
			if ($subscrip['lstatus'] == 0) {
				$options = array('0' => t('Unsubscribe'), '2' => t('Digest'), '3' => t('All Mail'));
				$status++;
			} else {
				$options = array('0' => t('Unsubscribe'), '1' => t('No mail'), '2' => t('Digest'), '3' => t('All Mail'));
			}
        	$subscrip=_mailman_manager_get_subscriptions($account->uid,$list[lid]);
			$fields['lists']['list'.trim($list[lid])] = array (
				'#type' => 'radios',
				'#title' => $list['name'],
				'#options' => $options,
				'#default_value' => $subscrip['lstatus']
			);
		}
	}
	if ($status != 0){
		$output2 = '<p>'.t('Your current email address in not subscribed to ').$status.t(' list(s)!<p>');
	}
	$output2 .= '</div>';
	$fields['lists']['#suffix'] = $output2;
	$fields['lists']['oldemail'] = array(
		'#type' => 'hidden',
		'#default_value' => $subscrip[lmail]
	);
	$fields['lists']['newemail'] = array(
		'#type' => 'hidden',
		'#default_value' =>	$account->mail
	);
	return $fields;
    break;
	}
	
  //Update and process list subscriptions;
    case 'update':
    if ($category=='mailman_manager'){
      $lists = _mailman_manager_get_lists();
      foreach ($lists as $list) {
	    $subscrip=_mailman_manager_get_subscriptions($account->uid,$list[lid]);
	    $listno='list'.trim($list[lid]);
        $query = "SELECT * FROM {mailman_users} WHERE uid = %d AND lid = %d";
        $result = db_query($query,$account->uid,$list[lid]);
        $subscrip = db_fetch_array($result);
        $password = $subscrip[lpass];
	    if ($subscrip[lstatus] != $edit[$listno]) {
	      _mailman_manager_update_subscriptions($account->uid,$list[lid],$edit[$listno],
		    $subscrip[lstatus],$account->mail,$password);   
	    }
      }
    return t('Your mailing list subscriptions have been updated');  
    }
  }
}

/**
 * Menu callback; displays the mailing list overview/editing page.
 */
function mailman_manager_admin() {
  $edit = $_POST['edit'];
  $op = $_POST['op'];

  if ($op == t('Add list')) {
    drupal_set_message(_mailman_manager_admin_save($edit));
  }
  else if ($op == t('Delete checked lists')) {
    drupal_set_message(_mailman_manager_admin_delete($edit));
  }
  print theme('page', _mailman_manager_admin_display());
}

/**
 * Prepare the mailing list admin form.
 */
function _mailman_manager_admin_display() {
  $output = '<div class="mailman_manager">';
  $lists = _mailman_manager_get_lists();
  if (count($lists) == 0) {
    $output .= '<p>'.t('There are no lists available for subscription.<table><tr>');
  } else {
    $output .= '<p>'.t('The following lists are available for subscription.<table><tr>');
	$output .= '<th width = 10%>ID</th>';
	$output .= '<th width = 30%>Name</th>';
	$output .= '<th width = 50%>Request/Admin Address</th>';
	$output .= '<th width = 10%>Delete?</th></tr>';
    foreach ($lists as $list) {
		$fields['del'.$list[lid]] = array(
			'#prefix' => '<tr><td>'.$list[lid].'</td><td>'.$list[name].'</td><td>'.$list[command].'</td><td>',
			'#type' => 'checkbox',
			'#default_value' => 0,
			'#suffix' => '</td></tr>'
		);
	}
  }
  $fields['Submit'] = array(
    '#prefix' => '<tr><td colspan=4>',
  	'#type' => 'submit',
	'#value' => 'Delete checked lists',
	'#suffix' => '</td></tr>'
  );
  $output2 = '</tr></table></div>';
  $fields2['mailman_manager_add_name'] = array (
  	'#title' => 'New list name',
  	'#type' => 'textfield',
  );
  $fields2['mailman_manager_add_reqaddress'] = array (
  	'#title' => 'New list address',
  	'#type' => 'textfield',
  );
  $fields2['mailman_manager_add_adminaddress'] = array (
  	'#title' => 'New list admin address',
  	'#type' => 'textfield',
  );
  $fields2['Submit'] = array (
  	'#type' => 'submit',
	'#value' => 'Add list',
  );
  return $output.drupal_get_form('Administer Mailing Lists',$fields).$output2.
  	drupal_get_form('Add Mailing List',$fields2);  
}

/**
 * Save new mailing list.
 */
function _mailman_manager_admin_save($edit) {
  $name = trim($edit['mailman_manager_add_name']);
  $command = trim($edit['mailman_manager_add_reqaddress']);
  $admin = trim($edit['mailman_manager_add_adminaddress']);  
  $query = "INSERT INTO {mailman_lists} (name,command,admin) VALUES ('%s', '%s', '%s')";
  if (db_query($query,$name,$command,$admin)){
    $watchdog = 'New Mailman list '.$name.' successfully created';
	watchdog('mailman man', $watchdog, 'WATCHDOG_NOTICE', NULL);
    return t('The mailing lists have been updated.');
  } else {
    $watchdog = 'Error in creating new Mailman list '.$name;
	watchdog('mailman man', $watchdog, 'WATCHDOG_ERROR', NULL);
    return t('Error creating mailing list.');
  }  
}

/**
 * Delete a mailing list.
 */
function _mailman_manager_admin_delete($edit) {
  $lists = _mailman_manager_get_lists();
  $listcount=0;
  foreach($lists as $list) {
    $delete=$edit['del'.$list[lid]];
	if ($delete) {
	  $query = "DELETE FROM {mailman_lists} WHERE lid = %d";
	  if (db_query($query,$list[lid])) {
        $watchdog = 'Successfully deleted Mailman list '.$list[lid];
		watchdog('mailman man', $watchdog, 'WATCHDOG_ERROR', NULL);
		$listcount++;
	  } else {
        $watchdog = 'Error in deleting Mailman list '.$list[lid];
		watchdog('mailman man', $watchdog, 'WATCHDOG_ERROR', NULL);
      }    	  
	}
  }
  return t('Successfully deleted '.$listcount.' mailing list(s).');	    
}

/**
 * Return array of objects of current mailing lists.
 */
function _mailman_manager_get_lists() {
  $result = db_query("SELECT * FROM {mailman_lists}");
  while ($list = db_fetch_array($result)){
    $lists[]=$list;
  }
return $lists;
}

/**
 * Return array of user's subscriptions to mailing lists.
 */
function _mailman_manager_get_subscriptions($uid,$lid) {
  $query = "SELECT * FROM {mailman_users} WHERE uid = %d AND lid = %d";
  $result = db_query($query,$uid,$lid);
  //If there are no entries for this user then set subscriptions to zero;
  //and return no mail button option for display;
  if (mysql_num_rows($result) == 0) {
    $query = "INSERT INTO {mailman_users} (uid,lid,lstatus) VALUES (%d, %d, %d)";
    db_query($query,$uid,$lid,0);
    $subscrip = array (
      uid => $uid,
      lid => $lid,
      lstatus => 0
    );
  } else {
 	$subscrip=db_fetch_array($result);
  }
return $subscrip;
}

/**
 * Update user's subscriptions to mailing lists.
 */
function _mailman_manager_update_subscriptions($uid,$lid,$lstatus,$oldstatus,$mail,$password) {
  $query = "UPDATE {mailman_users} SET lstatus = %d WHERE uid = %d AND lid = %d";
  db_query($query,$lstatus,$uid,$lid);
  switch ($lstatus) {

  // Unsubscribe selected;
  case 0:
    $command = "unsubscribe ".$password." address=".$mail;
    _mailman_manager_setdelivery($uid, $lid, $mail, $command);	
    $watchdog = 'User '.$uid.' unsuibscribed from list '.$lid;
    watchdog('mailman man', $watchdog, 'WATCHDOG_NOTICE', NULL);
  break;
    

  // No email selected;
  case 1:
    $command = "set authenticate ".$password." address=".$mail."\n";
    $command .= "set delivery off"; 
    _mailman_manager_setdelivery($uid, $lid, $mail, $command);	
    $watchdog = 'Subscription to list '.$lid.' for user '.$uid.' changed to no mail';
    watchdog('mailman man', $watchdog, 'WATCHDOG_NOTICE', NULL);
  break;
	
  //All mail selected;
  case 2: 
	if ($oldstatus == 0) {
	  _mailman_manager_subscribe($uid, $lid, $mail, 'nodigest');
	} else {
      $command = "set authenticate ".$password." address=".$mail."\n";
      $command .= "set delivery on\n"; 
      $command .= "set digest off"; 
	  _mailman_manager_setdelivery($uid,$lid,$mail,$command);
      $watchdog = 'Subscription to list '.$lid.' for user '.$uid.' changed to all mail';
      watchdog('mailman man', $watchdog, 'WATCHDOG_NOTICE', NULL);
	}
  break;
	
  //Digest selected;
  case 3: 
	if ($oldstatus == 0) {
	  _mailman_manager_subscribe($uid, $lid, $mail, 'digest');
	} else {
      $command = "set authenticate ".$password." address=".$mail."\n";
      $command .= "set delivery on\n"; 
      $command .= "set digest plain"; 
      _mailman_manager_setdelivery($uid,$lid,$mail,$command);	
      $watchdog = 'Subscription to list '.$lid.' for user '.$uid.' changed to digest';
      watchdog('mailman man', $watchdog, 'WATCHDOG_NOTICE', NULL);
    } 	 
  break;	   
  }
  return;
}

/**
 * Create a new subscription by sending request email to Mailman.
 */
function _mailman_manager_subscribe($uid, $lid, $mail, $digest){
  $query = "SELECT * FROM {mailman_lists} WHERE lid = %d";
  $result = db_query($query,$lid);
  $list = db_fetch_array($result);
  $commandaddress = $list[command];
  $adminaddress = $list[admin];
  $password = _mailman_manager_rand_str(5);
  $password .= trim($uid).substr($mail,0,1);
  $command = "subscribe ".$password." ".$digest." address=".trim($mail);
  $headers = "From: ".$adminaddress."\n";
  $headers .= "Bcc: ".$adminaddress."\n";  
  mail($commandaddress,'',$command,$headers);
  $query = "UPDATE {mailman_users} SET lmail = '%s', lpass = '%s' WHERE uid = %d AND lid = %d";
  if (db_query($query,$mail,$password,$uid,$lid)){
    $watchdog = 'New subscription to list '.$lid.' for user '.$uid.' completed successfully.';
	watchdog('mailman man', $watchdog, 'WATCHDOG_NOTICE', NULL);
  } else {
    $watchdog = 'New subscription to list '.$lid.' for user '.$uid.' failed.';
	watchdog('mailman man', $watchdog, 'WATCHDOG_ERROR', NULL);
  }	  
  return; 
}

/**
 * Update settings for a subscription by sending request email to Mailman.
 */
function _mailman_manager_setdelivery($uid, $lid, $mail, $command) {
  $query = "SELECT * FROM {mailman_lists} WHERE lid = %d";
  $result = db_query($query, $lid);
  $list = db_fetch_array($result);
  $commandaddress = $list[command];
  $adminaddress = $list[admin];
  $headers = "From: ".$adminaddress."\n";
  $headers .= "Bcc: ".$adminaddress."\n";  
    $watchdog = 'Mail command sent to Mailman to: '. $commandaddress.' Command: '.$command;
	watchdog('mailman man', $watchdog, 'WATCHDOG_NOTICE', NULL);
  mail($commandaddress,'',$command,$headers);
  return; 
}

/**
 * Generation of five character random text string for Mailman password.
 */
function _mailman_manager_rand_str($size)
{
   $feed = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
   for ($i=0; $i < $size; $i++)
   {
       $rand_str .= substr($feed, rand(0, strlen($feed)-1), 1);
   }
   return $rand_str;
}

?>